command:
  - uvicorn
  - main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: UC_CATALOG
    value: "main"
  - name: UC_SCHEMA_PUBLICO_ALVO
    value: "publico_alvo"
  - name: UC_SCHEMA_CLIENTE_360
    value: "cliente_360"
  - name: UC_SCHEMA_CAMPANHAS
    value: "campanhas"
  - name: UC_SCHEMA_LEADS
    value: "leads_campanha"
