CREATE TABLE IF NOT EXISTS main.customer_base.customer_master (
  cpf_cnpj STRING,
  customer_name STRING,
  tipo_cliente STRING,
  segmento STRING,
  subsegmento STRING,
  idade INT,
  sexo STRING,
  estado_civil STRING,
  cidade STRING,
  uf STRING,
  cep STRING,
  renda_mensal DECIMAL(18,2),
  faixa_renda STRING,
  patrimonio_estimado DECIMAL(18,2),
  data_relacionamento_inicio DATE,
  cluster_relacionamento STRING,
  is_prime BOOLEAN,
  is_exclusive BOOLEAN,
  is_pj BOOLEAN,
  is_varejo BOOLEAN,
  is_jovem_digital BOOLEAN,
  created_at TIMESTAMP
)
USING DELTA;
