-- Substitua <APP_SERVICE_PRINCIPAL> pelo service principal do Databricks App.

GRANT USE CATALOG ON CATALOG main TO `<APP_SERVICE_PRINCIPAL>`;
GRANT USE SCHEMA ON SCHEMA main.aplicacao_campanhas TO `<APP_SERVICE_PRINCIPAL>`;
GRANT USE SCHEMA ON SCHEMA main.base_clientes TO `<APP_SERVICE_PRINCIPAL>`;
GRANT USE SCHEMA ON SCHEMA main.cliente_360 TO `<APP_SERVICE_PRINCIPAL>`;
GRANT USE SCHEMA ON SCHEMA main.fontes_campanha TO `<APP_SERVICE_PRINCIPAL>`;
GRANT USE SCHEMA ON SCHEMA main.execucao_campanha TO `<APP_SERVICE_PRINCIPAL>`;

GRANT SELECT, MODIFY ON ALL TABLES IN SCHEMA main.aplicacao_campanhas TO `<APP_SERVICE_PRINCIPAL>`;
GRANT SELECT ON ALL TABLES IN SCHEMA main.base_clientes TO `<APP_SERVICE_PRINCIPAL>`;
GRANT SELECT ON ALL TABLES IN SCHEMA main.cliente_360 TO `<APP_SERVICE_PRINCIPAL>`;
GRANT SELECT ON ALL TABLES IN SCHEMA main.fontes_campanha TO `<APP_SERVICE_PRINCIPAL>`;
GRANT SELECT, MODIFY ON ALL TABLES IN SCHEMA main.execucao_campanha TO `<APP_SERVICE_PRINCIPAL>`;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA main.execucao_campanha TO `<APP_SERVICE_PRINCIPAL>`;
